### ISSUE TITLE
make revisionTime optional

### ISSUE THREAD

**Issue by rsc** [kardianos/vendor-spec#30]
It is not clear to me why revisionTime is needed, when it can be fetched from the remote source control given the revision hash. I can see that it might be interesting, but not why it is required.

Is it optional? Can it be made explicitly optional?

**Comment by kardianos** [comment]
I think it is explicitly optional in:
https://github.com/kardianos/vendor-spec#revision-and-revisiontime-fields

```
Both revision fields are optional.
```

I could change that to read:

```
Both revision and revisionTime fields are optional.
```

**Comment by rsc** [comment]
I see. I was confused by "The following struct describes the minimum fields that must be present in the json file:". Maybe that should say "the well-known fields:".

**Comment by kardianos** [comment]
As a maintainer I like revisionTime to be present. Just yesterday I used that rather than the hash to determine if I should update a dependency. I could have used the hash, but dates were faster. I also want to anticipate not always having the remote repo fully readily present 5+ years from now and still want to know roughly when it was updated. I have had other (non-Go) projects where that would have need nice.

**Comment by kardianos** [comment]
RE: "well-known fields"
Good point. I'll update shortly.

**Comment by mattfarina** [comment]
When I see this field I see something I would want a machine to write. My tooling that updates my packages based on the versions I specified in the file. Should both a person and tooling be writing the same file that's checked into a VCS?

I know tools like composer, for PHP, writes a second file full of machine information (`composer.lock` file).

**Comment by kardianos** [comment]
@mattfarina That is how many tools today work.

What I would recommend is for the user to write zero files in many cases and just use a tool to deal with packages. Then if you want to specify a particular revision from maybe you would specify someday `go vendor update -u github.com/user/proj/pkg@1.2.3-beta` and let the tool handle writing this file.

But this file should also be simple enough to be read and written by a human.

However, I do acknowledge that what you describe is how many tools work today. I still need to implement fetching remote packages in my tool; I could be mistaken in this design.

**Comment by mattfarina** [comment]
There's something we should be explicit about that were not talking about. That's vendor vs vendoring. What I mean is that vendor is from someone else. A vendor. Vendoring is storing someone else's code in your repo. Using `go vendor update -u github.com/user/proj/pkg@1.2.3-beta` looks like it's for vendoring.

The debate where to use vendoring or not is like debating emacs vs vi. It would be good to support both cases.

What do you think about this?

**Comment by kardianos** [comment]
@mattfarina Are you saying you might have a tool that fetches revisions or versions before a build, but isn't checked in? But the "lock" file is checked in so it can be fetched, right? I do plan to support this with kardianos/govendor tool. So long as the vendor-spec contains a revision or version, there shouldn't be an issue.

So the mythical command `go vendor update ...` may copy the package, or it could just update the vendor-spec file. My point was that the vendor-spec file could serve as a lock file and rather then creating a separate "human editable" file, just use a command normally edit it. I'm saying the paradigm of "lock + human file" you are used to in other languages may not be necessary.

**Comment by mattfarina** [comment]
@kardianos How would you handle the case of using something like `go get -vendor ./...` and versions? The idea of fetching all the needed packages for the vendor directory and getting the versions right.

If you're not familiar, I work on a tool named [Glide](https://github.com/masterminds/glide) where we handle these cases right now. I don't think the package spec is perfect (with naming conventions) but we are handling all the use cases thrown at us right now.

**Comment by kardianos** [comment]
@mattfarina I appreciate that you are building a tool and aren't coming from just a theoretical standpoint. I built the tool github.com/kardianos/govendor in tandum with creating this spec, I didn't want to spec something in a vacuum.

I suspect our differences come from different workflow designs.
- In glide you appear to promote pre-specifying what dependencies you want, fetch them, then build the packages. With govendor the assumed workflow was write go code, ask govendor to copy dependencies locally and record version information in vendor-spec (you could still choose to not check in the vendor code and just rely on the vendor-spec).
- In the glide yaml file you appear to put the "repo" package path first, then put the package paths under that. In govendor repo is never explicitly stated, all packages are top level.

So to answer your question, how would vendor-spec handle `go get -vendor ./...`, I'm assuming that this would attempt to read a vendor-spec file and fetch the packages it specifies in to the "vendor" directory? Or maybe because you used "./..." you are reading the local packages iimports and you are asking it to vendor the external dependencies? I don't see a problem in either one of those cases.

Maybe you are assuming that you wish to both specify versions for particular packages and fetch them all at once, thus requiring a human created spec file that specifies versions? If so, rather then creating the human editable file by hand, just run a few commands that specifies the versions then say fetch... That appears to be equivalent workflow. But I could be misinterpreting what you are saying.

**Comment by mattfarina** [comment]
For reference, in Glide we have commands to help manage the file. For example, `glide get golang.org/x/net` that fetches a package and adds it to the config file as minimally as possible. But, we chose yaml because it's easy for people to read and write it.

The `repo` and `vcs` properties are optional. They let you have complete control of the repo if you want that. For example, if you have an imported package that you're working on in conjunction with the main repo you could set the `repo` to something like `git@github.com/foo/bar` and the `vcs` to `git`. Then, when you `install` with glide or want to push to the sub-packages repo it's all there and working.

Something similar is in package managers from other languages. It's not an uncommon use case. Since Go can me on *nix and Windows you also want a common cross platform way to handle this.

I've had the "fun" of working with package management with 5 different languages/platforms in the past 5 years. I just trying to apply what I've learned from there to this space in Go.

**Comment by kardianos** [comment]
@mattfarina 
- JSON was chosen because it is easier to read then XML and is in the standard library (otherwise I would have chosen toml).
- I agree that the fields you have works, I dispute they are all needed. The vendor-spec allows custom fields it requires tools to care on if unknown.
- I agree I want solutions that are totally cross platform. I test on both Linux and Windows.
- Most of us have experience with many different package managers. I'm cautions in how much direct inspiration we should take from them do to how Go is compiled, dependencies are the developers problem, never the runtime's problem. Go also requires less external specification due to how imports are declared.

**Comment by mattfarina** [comment]
@kardianos is the toolchain around managing dependencies to support the compiler or to support developers in managing their dependencies?

Can you explain how Go being compiled creates a difference in managing dependencies compared to something like Composer for PHP or npm for node.js? I'm not sure I see how that makes a difference.

**Comment by kardianos** [comment]
@mattfarina
In an absolute sense, you are correct, developers are users and they need to compile your code, just like end-users need all the sources for source based languages. So if you consider all distribution to be source based and users will fetch their code in real-time from github and we pray that github and the project's dependencies are still around in 8 years, then no, there is no difference.

**Comment by akavel** [comment]
Just for the record: I believe a great example for usefulness of revisionTime is the case of the recent winding down of code.google.com, and the ensuing wave of project migrations to github. As a side effect, many of the projects had to be forcefully migrated from Mercurial to Git, thus making the contents of the revision field potentially useless, while making the revisionTime field very useful for pinpointing the same revision post-migration.
