### ISSUE TITLE
Vendor-spec should become a go proposal

### ISSUE THREAD

**Issue by davecheney** [kardianos/vendor-spec#33]
The  vendor-spec is now being used inside the Go project. 

https://github.com/golang/go/commit/10efac8782a053f29a1c63ca19986cc638710f07

This means it is now the time for the vendor-spec to go through the go proposal process for ratification.

**Comment by mattfarina** [comment]
@davecheney What are the chances of making the vendor-spec more usable first? And cleaning up the usage in Go itself, too? For those of us coming from other systems there are some useful changes we could make.

**Comment by kardianos** [comment]
@davecheney I suspect Russ wanted to get a feel for using it as well as record the revision. After he added that he also submitted a few issues to vendor-spec. I don't understand why that check-in means it is necessary for it to go through the new go proposal process for ratification. My concern is that you are stating this, rather than requesting it, in order to influence it in a different context. If you do have existing concerns, please do voice them. In the past you mentioned adding a "version" field; I will acknowledge history and issues (even closed) in any future proposal.

Although this is just a vendor-spec, I also want to include how this is currently used and how it may be used in the future. Specific use cases and workflow are incredibly important.

So stay tuned, but it isn't ready yet. Both @rsc and @mattfarina have raised points that should be addressed in some form or another.

**Comment by rsc** [comment]
Regarding the uses in the Go repos, I needed to write down what version of the code I was manually copying in. It seemed like using "vendor-spec" format was better than wrting an ad-hoc text file. I also wanted to understand better what it would be like to use in practice, and that helped: as @kardianos noted I found a few things that might be improved. 

In the long term, we want all the tools that copy code into or out of vendor/ subtrees understand and prefer vendor.json as the metadata format, so there certainly needs to be agreement similar to what you'd get by going through the proposal process. If the vendor file were started today it would make sense to start as a Proposal, but I think the history here justifies leaving the spec and the discussion in this GitHub repo for now and continuing to discuss changes here. There's already a lot of discussion and history here; it might as well continue here until things converge on a "1.0" of sorts. And then it will certainly make sense to put into the proposal process for indexing and ease of access.

**Comment by davecheney** [comment]
@kardianos 

> My concern is that you are stating this, rather than requesting it, in order to influence it in a different context. 

This is unrelated to golang/go#12302.

We have a Go proposal process now, we didn't when you started the vendor-spec, and I think the proposal process is the right way to proceed to have the vendor-spec ratified.

**Comment by davecheney** [comment]
@kardianos you are right, this is too early for formalisation. Please accept my apologies for the misunderstanding.
